name: Generate manual

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Additional Software
      run: |
        sudo apt install libreoffice --no-install-recommends  --no-install-suggests
        sudo apt install texlive-latex-base --no-install-recommends  --no-install-suggests
        pip3 install Sphinx
        pip3 install sphinx-rtd-theme
    - name: Generate PDF from libreoffice document
      run: |
        cd EnrouteManual
        libreoffice --convert-to pdf IntroducingEnroute.odt
    - name: Generate sphinx manual
      run: |
        cd manual
        make linkcheck
        make html
        make latexpdf
        make epub
    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: EnrouteManual
        TARGET_FOLDER: manual
