name: Generate PDF version of manual

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install Additional Software
      run: |
        sudo apt install libreoffice
    - name: Generate PDF
      run: |
        cd EnrouteManual
        libreoffice --convert-to pdf IntroducingEnroute.odt
    - name: Publish Documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        REPOSITORY_NAME: enroute
        BRANCH: gh-pages
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: .
        TARGET_FOLDER: assets/pdf
