name: Generate manual

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Install Additional Software
      run: |
        sudo apt install latexmk texlive-base texlive-fonts-recommended texlive-latex-base texlive-latex-extra texlive-latex-recommended tex-gyre --no-install-recommends  --no-install-suggests
        pip3 install Sphinx
        pip3 install sphinx-material
    - name: Generate sphinx manual
      run: |
        export PATH=~/.local/bin:$PATH
        cd manual
        make epub
        make html
        make latexpdf
        mv _build/latex/enrouteflightnavigation.pdf _build/manual.pdf
        mv _build/epub/EnrouteFlightNavigation.epub _build/manual.epub
        mv _build/html _build/manual
        rm -rf _build/doctrees _build/epub _build/latex
    - name: Publish sphinx documentation
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        BRANCH: master
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        FOLDER: manual/_build
        TARGET_FOLDER: docs
