name: Check for missing translations

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '17 23 * * 5'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Check for missing translations
      run: |
        ./checkForMissingTranslations.py ${{ secrets.GITHUB_TOKEN }}
