name: Check for missing translations

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Check for missing translations
      run: |
        ./checkForMissingTranslations.py ${{ secrets.GITHUB_TOKEN }}
